# Generated by Django 4.2.8 on 2023-12-27 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0002_alter_wallet_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name_plural": "Currencies"},
        ),
    ]
