# Generated by Django 4.2.8 on 2024-01-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0004_rename_amount_transaction_amount_paid_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.AlterModelOptions(
            name="currency",
            options={},
        ),
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(default="test notification", max_length=200),
            preserve_default=False,
        ),
    ]
