# Generated by Django 4.2.8 on 2024-01-11 18:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0005_delete_payment_alter_currency_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="amount_transferred",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="service_fee",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
