# Generated by Django 4.2.8 on 2024-01-15 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0006_remove_transaction_amount_transferred_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionlog",
            name="prev_status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prev_status",
                to="wallet.transactionstatus",
            ),
        ),
    ]
