# Generated by Django 4.2.8 on 2024-01-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0007_alter_transactionlog_prev_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="paymentprovider",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="transactionstatus",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="transactiontype",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
