# Generated by Django 4.2.8 on 2024-01-17 22:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "wallet",
            "0009_transaction_notes_transaction_payment_account_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name_plural": "Currencies"},
        ),
        migrations.AlterModelOptions(
            name="transactionstatus",
            options={"verbose_name_plural": "Transaction statuses"},
        ),
    ]
