# Generated by Django 4.2.8 on 2024-01-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0010_alter_currency_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankTransferDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=200)),
                ("account_name", models.CharField(max_length=200)),
                ("account_number", models.CharField(max_length=200)),
                ("CBU", models.CharField(max_length=200)),
                ("branch", models.CharField(max_length=200)),
                ("alias", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
