# Generated by Django 4.2.8 on 2024-01-22 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0011_banktransferdetails"),
        ("wallet", "0011_transactionapproval"),
    ]

    operations = []
