# Generated by Django 4.2.8 on 2024-01-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="xpuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("00", "Femenino"), ("01", "Masculino")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="xpuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
