# Generated by Django 4.2.8 on 2024-01-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="xpuser",
            name="kyc_status",
            field=models.IntegerField(
                choices=[(0, "Invalid"), (1, "Valid")], default=0
            ),
        ),
    ]
