# Generated by Django 4.2.8 on 2024-01-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_xpuser_gender_alter_xpuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xpuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("00", "Female"),
                    ("01", "Male"),
                    ("3", "Heart"),
                    ("4", "Club"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
