# Generated by Django 4.2.8 on 2024-01-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_xpuser_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xpuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("00", "Man"),
                    ("01", "Woman"),
                    ("02", "He Trans"),
                    ("03", "She Trans"),
                    ("04", "Couple Mw"),
                    ("05", "Couple Ww"),
                    ("06", "Couple Mm"),
                    ("07", "Couple Tw"),
                    ("08", "None"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
