# Generated by Django 4.2.8 on 2024-01-18 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_xpuser_kyc_status"),
        ("users", "0004_alter_xpuser_gender"),
    ]

    operations = []
